export const mockDashboardData = {
  totalProducts: 48,
  totalStockValuation: 284750.00,
  lowStockCount: 4,
  pendingReceipts: 6,
  pendingDeliveries: 9,
  activeTransfers: 3,
  recentActivities: [
    {
      _id: 'act-101',
      transactionType: 'RECEIPT',
      referenceNumber: 'REC-982314',
      product: { name: 'Industrial OLED Display 15"', sku: 'DSP-OLED-15' },
      warehouse: { name: 'Central Distribution Hub', code: 'WH-CENTRAL' },
      quantityChange: 150,
      createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    },
    {
      _id: 'act-102',
      transactionType: 'DELIVERY',
      referenceNumber: 'DEL-441209',
      product: { name: 'Microcontroller MCU-X4', sku: 'CHIP-MCU-X4' },
      warehouse: { name: 'East Logistics Center', code: 'WH-EAST' },
      quantityChange: -80,
      createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    },
    {
      _id: 'act-103',
      transactionType: 'TRANSFER_IN',
      referenceNumber: 'TRF-110294',
      product: { name: 'Lithium Pack 5000mAh', sku: 'BAT-LI-5000' },
      warehouse: { name: 'West Storage Depot', code: 'WH-WEST' },
      quantityChange: 50,
      createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    },
    {
      _id: 'act-104',
      transactionType: 'ADJUSTMENT',
      referenceNumber: 'ADJ-008231',
      product: { name: 'High Precision Servo Motor', sku: 'MTR-SRV-90' },
      warehouse: { name: 'Central Distribution Hub', code: 'WH-CENTRAL' },
      quantityChange: -3,
      createdAt: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    },
    {
      _id: 'act-105',
      transactionType: 'RECEIPT',
      referenceNumber: 'REC-982110',
      product: { name: 'Solid State Relay 25A', sku: 'RLY-SSR-25' },
      warehouse: { name: 'East Logistics Center', code: 'WH-EAST' },
      quantityChange: 200,
      createdAt: new Date(Date.now() - 1000 * 60 * 640).toISOString(),
    },
  ],
};

export const mockProducts = [
  {
    _id: 'prod-1',
    name: 'Industrial OLED Display 15"',
    sku: 'DSP-OLED-15',
    category: 'Displays',
    costPrice: 120.00,
    sellingPrice: 195.00,
    totalQuantity: 240,
    unitOfMeasure: 'Units',
    minReorderLevel: 25,
    warehouseStock: [
      { warehouse: { name: 'Central Hub', code: 'WH-CENTRAL' }, quantity: 180 },
      { warehouse: { name: 'East Logistics', code: 'WH-EAST' }, quantity: 60 },
    ],
  },
  {
    _id: 'prod-2',
    name: 'Microcontroller MCU-X4 ARM 64-bit',
    sku: 'CHIP-MCU-X4',
    category: 'Semiconductors',
    costPrice: 14.50,
    sellingPrice: 28.00,
    totalQuantity: 1250,
    unitOfMeasure: 'Units',
    minReorderLevel: 200,
    warehouseStock: [
      { warehouse: { name: 'Central Hub', code: 'WH-CENTRAL' }, quantity: 850 },
      { warehouse: { name: 'West Storage', code: 'WH-WEST' }, quantity: 400 },
    ],
  },
  {
    _id: 'prod-3',
    name: 'Lithium Pack 5000mAh 14.8V',
    sku: 'BAT-LI-5000',
    category: 'Power & Batteries',
    costPrice: 38.00,
    sellingPrice: 65.00,
    totalQuantity: 12,
    unitOfMeasure: 'Packs',
    minReorderLevel: 50,
    warehouseStock: [
      { warehouse: { name: 'Central Hub', code: 'WH-CENTRAL' }, quantity: 12 },
    ],
  },
  {
    _id: 'prod-4',
    name: 'High Precision Servo Motor 20Nm',
    sku: 'MTR-SRV-90',
    category: 'Actuators',
    costPrice: 85.00,
    sellingPrice: 149.00,
    totalQuantity: 5,
    unitOfMeasure: 'Units',
    minReorderLevel: 15,
    warehouseStock: [
      { warehouse: { name: 'Central Hub', code: 'WH-CENTRAL' }, quantity: 5 },
    ],
  },
  {
    _id: 'prod-5',
    name: 'Optoisolated Solid State Relay 25A',
    sku: 'RLY-SSR-25',
    category: 'Switches & Relays',
    costPrice: 8.20,
    sellingPrice: 18.50,
    totalQuantity: 420,
    unitOfMeasure: 'Units',
    minReorderLevel: 50,
    warehouseStock: [
      { warehouse: { name: 'East Logistics', code: 'WH-EAST' }, quantity: 420 },
    ],
  },
  {
    _id: 'prod-6',
    name: 'Fiber Optic Transceiver 10Gbps SFP+',
    sku: 'NET-SFP-10G',
    category: 'Networking',
    costPrice: 42.00,
    sellingPrice: 79.00,
    totalQuantity: 88,
    unitOfMeasure: 'Units',
    minReorderLevel: 20,
    warehouseStock: [
      { warehouse: { name: 'Central Hub', code: 'WH-CENTRAL' }, quantity: 88 },
    ],
  },
];

export const mockReceipts = [
  {
    _id: 'rec-1',
    receiptNumber: 'REC-982314',
    supplier: { name: 'Apex Display Technologies Ltd.' },
    warehouse: { name: 'Central Distribution Hub', code: 'WH-CENTRAL' },
    status: 'done',
    scheduledDate: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    totalAmount: 18000,
  },
  {
    _id: 'rec-2',
    receiptNumber: 'REC-982405',
    supplier: { name: 'Nordic Semiconductor Global' },
    warehouse: { name: 'East Logistics Center', code: 'WH-EAST' },
    status: 'ready',
    scheduledDate: new Date(Date.now() + 1000 * 60 * 360).toISOString(),
    totalAmount: 14500,
  },
  {
    _id: 'rec-3',
    receiptNumber: 'REC-982512',
    supplier: { name: 'Shenzhen Power Cell Corp' },
    warehouse: { name: 'West Storage Depot', code: 'WH-WEST' },
    status: 'waiting',
    scheduledDate: new Date(Date.now() + 1000 * 60 * 1440).toISOString(),
    totalAmount: 9200,
  },
];

export const mockDeliveries = [
  {
    _id: 'del-1',
    deliveryNumber: 'DEL-441209',
    customer: { name: 'Tesla Automation & Robotics' },
    warehouse: { name: 'Central Distribution Hub', code: 'WH-CENTRAL' },
    status: 'done',
    scheduledDate: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    totalAmount: 2240,
  },
  {
    _id: 'del-2',
    deliveryNumber: 'DEL-441315',
    customer: { name: 'Siemens Industrial Solutions' },
    warehouse: { name: 'East Logistics Center', code: 'WH-EAST' },
    status: 'ready',
    scheduledDate: new Date(Date.now() + 1000 * 60 * 180).toISOString(),
    totalAmount: 6850,
  },
  {
    _id: 'del-3',
    deliveryNumber: 'DEL-441420',
    customer: { name: 'Honeywell Aerospace Group' },
    warehouse: { name: 'West Storage Depot', code: 'WH-WEST' },
    status: 'waiting',
    scheduledDate: new Date(Date.now() + 1000 * 60 * 720).toISOString(),
    totalAmount: 12100,
  },
];

export const mockTransfers = [
  {
    _id: 'trf-1',
    transferNumber: 'TRF-110294',
    fromWarehouse: { name: 'Central Distribution Hub', code: 'WH-CENTRAL' },
    toWarehouse: { name: 'East Logistics Center', code: 'WH-EAST' },
    status: 'done',
    scheduledDate: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
  },
  {
    _id: 'trf-2',
    transferNumber: 'TRF-110350',
    fromWarehouse: { name: 'East Logistics Center', code: 'WH-EAST' },
    toWarehouse: { name: 'West Storage Depot', code: 'WH-WEST' },
    status: 'ready',
    scheduledDate: new Date(Date.now() + 1000 * 60 * 420).toISOString(),
  },
];

export const mockAdjustments = [
  {
    _id: 'adj-1',
    adjustmentNumber: 'ADJ-008231',
    warehouse: { name: 'Central Distribution Hub', code: 'WH-CENTRAL' },
    status: 'done',
    adjustmentDate: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
  },
  {
    _id: 'adj-2',
    adjustmentNumber: 'ADJ-008290',
    warehouse: { name: 'West Storage Depot', code: 'WH-WEST' },
    status: 'draft',
    adjustmentDate: new Date().toISOString(),
  },
];

export const mockLedger = [
  {
    _id: 'led-1',
    transactionType: 'RECEIPT',
    referenceNumber: 'REC-982314',
    product: { name: 'Industrial OLED Display 15"', sku: 'DSP-OLED-15' },
    warehouse: { name: 'Central Distribution Hub', code: 'WH-CENTRAL' },
    quantityChange: 150,
    previousQuantity: 90,
    newQuantity: 240,
    unitCost: 120.00,
    totalCost: 18000.00,
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    _id: 'led-2',
    transactionType: 'DELIVERY',
    referenceNumber: 'DEL-441209',
    product: { name: 'Microcontroller MCU-X4 ARM', sku: 'CHIP-MCU-X4' },
    warehouse: { name: 'East Logistics Center', code: 'WH-EAST' },
    quantityChange: -80,
    previousQuantity: 1330,
    newQuantity: 1250,
    unitCost: 28.00,
    totalCost: 2240.00,
    createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
  },
  {
    _id: 'led-3',
    transactionType: 'TRANSFER_IN',
    referenceNumber: 'TRF-110294',
    product: { name: 'Lithium Pack 5000mAh', sku: 'BAT-LI-5000' },
    warehouse: { name: 'West Storage Depot', code: 'WH-WEST' },
    quantityChange: 50,
    previousQuantity: 0,
    newQuantity: 50,
    unitCost: 38.00,
    totalCost: 1900.00,
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
];
